/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsHeartDiseasePredictionRouteImport } from './routes/projects/heart-disease-prediction'
import { Route as ProjectsEduvaultAiRouteImport } from './routes/projects/eduvault-ai'
import { Route as ProjectsDiskSchedulingSimulatorRouteImport } from './routes/projects/disk-scheduling-simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHeartDiseasePredictionRoute =
  ProjectsHeartDiseasePredictionRouteImport.update({
    id: '/projects/heart-disease-prediction',
    path: '/projects/heart-disease-prediction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsEduvaultAiRoute = ProjectsEduvaultAiRouteImport.update({
  id: '/projects/eduvault-ai',
  path: '/projects/eduvault-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDiskSchedulingSimulatorRoute =
  ProjectsDiskSchedulingSimulatorRouteImport.update({
    id: '/projects/disk-scheduling-simulator',
    path: '/projects/disk-scheduling-simulator',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/disk-scheduling-simulator': typeof ProjectsDiskSchedulingSimulatorRoute
  '/projects/eduvault-ai': typeof ProjectsEduvaultAiRoute
  '/projects/heart-disease-prediction': typeof ProjectsHeartDiseasePredictionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/disk-scheduling-simulator': typeof ProjectsDiskSchedulingSimulatorRoute
  '/projects/eduvault-ai': typeof ProjectsEduvaultAiRoute
  '/projects/heart-disease-prediction': typeof ProjectsHeartDiseasePredictionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/disk-scheduling-simulator': typeof ProjectsDiskSchedulingSimulatorRoute
  '/projects/eduvault-ai': typeof ProjectsEduvaultAiRoute
  '/projects/heart-disease-prediction': typeof ProjectsHeartDiseasePredictionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/disk-scheduling-simulator'
    | '/projects/eduvault-ai'
    | '/projects/heart-disease-prediction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/disk-scheduling-simulator'
    | '/projects/eduvault-ai'
    | '/projects/heart-disease-prediction'
  id:
    | '__root__'
    | '/'
    | '/projects/disk-scheduling-simulator'
    | '/projects/eduvault-ai'
    | '/projects/heart-disease-prediction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsDiskSchedulingSimulatorRoute: typeof ProjectsDiskSchedulingSimulatorRoute
  ProjectsEduvaultAiRoute: typeof ProjectsEduvaultAiRoute
  ProjectsHeartDiseasePredictionRoute: typeof ProjectsHeartDiseasePredictionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/heart-disease-prediction': {
      id: '/projects/heart-disease-prediction'
      path: '/projects/heart-disease-prediction'
      fullPath: '/projects/heart-disease-prediction'
      preLoaderRoute: typeof ProjectsHeartDiseasePredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/eduvault-ai': {
      id: '/projects/eduvault-ai'
      path: '/projects/eduvault-ai'
      fullPath: '/projects/eduvault-ai'
      preLoaderRoute: typeof ProjectsEduvaultAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/disk-scheduling-simulator': {
      id: '/projects/disk-scheduling-simulator'
      path: '/projects/disk-scheduling-simulator'
      fullPath: '/projects/disk-scheduling-simulator'
      preLoaderRoute: typeof ProjectsDiskSchedulingSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsDiskSchedulingSimulatorRoute: ProjectsDiskSchedulingSimulatorRoute,
  ProjectsEduvaultAiRoute: ProjectsEduvaultAiRoute,
  ProjectsHeartDiseasePredictionRoute: ProjectsHeartDiseasePredictionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
